Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "spec/**/*_spec.rb"

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*_spec.rb"

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
